Support OpenJDK flavor of Rhino
Previously, our load function would fail on OpenJDK with the cryptic error:

sun.org.mozilla.javascript.EvaluatorException: Function importClass must be called with a class; had "[JavaPackage sun.org.mozilla.javascript.internal.Context]" instead.

Which was caused by the fact that the wrong fully qualified Context class name
was returned: OpenJDK uses sun.org.mozilla.javascript.Context, whereas Oracle
Java uses sun.org.mozilla.javascript.internal.Context.

This may remain a lurking issue with OpenJDK-8-flavored Nashorn... but I don't
have an OpenJDK 8 installation to use for testing at this moment. Hopefully
this commit will be enough of a hint to fix similar problems in the future.